[project]
name = "Programmier-bung-2"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "J4nickH", email = "ha1220@mci4me.at"},
]
dependencies = ["numpy>=2.0.2", "matplotlib>=3.9.4"]
requires-python = ">=3.9"
readme = "README.md"
license = {text = "MIT"}


[tool.pdm]
distribution = false
