def bubble_sort(arr): #generated by vscode-auto-complete
    """
    Sorts an array using the bubble sort algorithm.
    
    Parameters:
    arr (list): The array to be sorted.
    
    Returns:
    list: The sorted array.
    """
    n = len(arr)
    for i in range(n):
        for j in range(0, n-i-1):
            if arr[j] > arr[j+1]:
                arr[j], arr[j+1] = arr[j+1], arr[j]
    return arr[::-1]        

if __name__ == "__main__": 
    import numpy as np
    data = np.array([5, 2, 9, 1, 5, 6])
    sorted_data = bubble_sort(data)
    print("Sorted data:", sorted_data)
    # Expected Output: Sorted data: [9 6 5 5 2 1]